# Generated by Django 5.0.2 on 2024-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='事件标题')),
                ('area', models.CharField(max_length=255, null=True, verbose_name='地点')),
                ('detail', models.CharField(max_length=255, null=True, verbose_name='事件内容')),
                ('more', models.BooleanField(default=False, verbose_name='是否为周期事件')),
                ('duration', models.CharField(max_length=255, null=True, verbose_name='持续时间')),
                ('user_id', models.IntegerField(null=True, verbose_name='该事件对应的用户ID')),
                ('freq', models.CharField(max_length=255, verbose_name='循环周期')),
                ('interval', models.IntegerField(verbose_name='循环间隔')),
                ('dtstart', models.DateTimeField(verbose_name='开始时间')),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='事件次数')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='密码')),
                ('email', models.CharField(max_length=64, null=True, unique=True, verbose_name='邮箱')),
                ('role', models.IntegerField(default=0, verbose_name='角色')),
                ('pic', models.CharField(default='/static/user_default.png', max_length=300, verbose_name='头像')),
                ('status', models.IntegerField(default=1, verbose_name='账号状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
        ),
    ]
